#!/bin/bash

mkdir /tmp/owbicons
cd /tmp/owbicons
wget http://dl.dropbox.com/u/7793460/nouveGnomeGray-latest.tar.bz2
tar -xvf nouveGnomeGray-latest.tar.bz2
cd nouveGnomeGray
sed -i 's/nouveGnomeGray/nouveGnomeBrass/g' index.theme
echo -e "\n\nChange nouveGnomeGray to nouveGnomeBrass" >> README

find -iname "*.png" | while read file
	do

	if [ ! -L "$file" ];then
		echo Converting "$file" ...
		convert "$file"  -fill "#000000" -colorize 0,0,100 -modulate 94,140,97 "$file"
	fi
done

cd ..
mv nouveGnomeGray nouveGnomeBrass
cp -r nouveGnomeBrass ~/.icons
tar -czvf /tmp/nouveGnomeBrass.tar.gz nouveGnomeBrass
rm -r /tmp/owbicons

