#!/bin/bash

#$1=Video page

wget "$1" -O out.html

#get the swf data

slice=$(cat out.html | grep "var swfArgs" | gawk -Fvideo_id: '{print $2}')
page=$(echo "$slice" | gawk -F: '{print $1}')
data=$(echo "$slice" | gawk -F: '{print $3}')

#extract the page title to use as filename
title=$(cat out.html | grep "<title>" | sed 's/[</]*title[>]//g' |gawk -F\- '{print $2 "-" $3}')

#This is youtubes swf link
#
#var swfArgs = {hl:'en',BASE_YT_URL:'http://uk.youtube.com/',video_id:'OgHx6bfjBD4',l:'164',t:'OEgsToPDskLAnj3bwVO68Ye3kEPsDcgB',sk:'5hTQOYHn0bsmAj-kob8rewC'};
#                                                                      ^^^^^^^^^^^=page        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^=data
#or :
#var swfArgs = {hl:'en',video_id:'-B3UrB_dex8',l:'239',t:'OEgsToPDskJe5Ey5a1F_RLsT87EuJ2lO',sk:'hHk57XiSG-RHJ_u6mu_XhAC'};
#                                 ^^^^^^^^^^^=page        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^=data

#clean up the strings and get rid of unwanted characters
page=${page:1:${#page}-4}
data=${data:1:${#data}-5}
title=${title##" "}

echo "XXXXXXXXXXXXXXXXXXXXXXXXXXXX"
echo "Page=$page"
echo "SWF Data=$data"
echo "Using \"$title\" As Filename"
echo "Command Used=wget --wait=1 --random-wait --continue --post-data video_id=\"$page&t=$data\" http://youtube.com/get_video -O \"${title}\".flv"
echo "XXXXXXXXXXXXXXXXXXXXXXXXXXXX"

wget --wait=1 --random-wait --continue --post-data video_id="$page&t=$data" http://youtube.com/get_video -O "${title}"

