#!/bin/bash

#BACKGROUNDDIR="/home/keithhedger/Documents/Themes/themedata"
BACKGROUNDDIR="/media/BackingStore/Pictures/Egypt/luxorkarnak"
DATADIR="/home/keithhedger/Documents/Themes/themedata"

BACKGROUNDFILES=(  $(find $BACKGROUNDDIR | grep -i JPG) )
MAXFILES=${#BACKGROUNDFILES[@]}

rm $DATADIR/background

NUMBER=$RANDOM
BACK=${BACKGROUNDFILES[ $(( NUMBER %=  MAXFILES ))]}
cp $BACK $DATADIR/temppic
ln -sf $DATADIR/temppic $DATADIR/background

